### PR TITLE
Fix license file creation

### PR DESCRIPTION
**Pull request by MaKaNu**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Documentation in `docs` is updated

**Description of changes**

I total agree with your suggestion from #29 and as promised here is my PR.

I have added the following new license files:

- LICENSE_MIT
- LICENSE_BSD
- LICENSE_ISC
- LICENSE_APACHE
- LICENSE_GPL

The content was either from the official raw txt files (GPL and APACHE) or from Github.
The previous LICENSE file is now deleted.

Further, I have update post generation script to handle the different licenses and added tests for the various commands.

The changes do not affect the user directly, because now only the correct licenses are provided.

Just to inform:
Apache and GPLv3 are provided as are, since both don't include a copyright from the developer. They both only include information how to handle the licenses in the projects correctly. Changing those Licenses is not permitted, so they don't author and copyright of the users are not included.

### CODE REVIEW

**Comment by fpgmaas** [comment]
Sorry for the late reply! This looks great. Are you able to pull `main` and run the `pre-commit` hooks?

**Comment by MaKaNu** [comment]
done. Having pre-commit only helps if I had installed the hooks. XD

**Comment by fpgmaas** [comment]
@MaKaNu Hey, sorry; looks like there is still a merge confict with `uv.lock`. Could you try to fetch latest changed from upstream? You can then just do `rm uv.lock && uv lock` to fix the conflict.

**Comment by MaKaNu** [comment]
In the meantime, two other versions were already updated again. But now it seems fine

**Pull request merged**
